In [12]:
# The first task
import numpy as np
array = np.random.randint(low=0, high=1000, size=(5, 5))
print("The original matrix:", array, sep="\n", end="\n\n")
massif = array[np.argsort(array[:, 2])]
print("The sorted matrix:", massif, sep="\n")

The original matrix:
[[816  46 395  21 875]
 [588 814 524 278 530]
 [452 932  99  45 529]
 [254 753 715 752 746]
 [708 681 759 900 500]]

The sorted matrix:
[[452 932  99  45 529]
 [816  46 395  21 875]
 [588 814 524 278 530]
 [254 753 715 752 746]
 [708 681 759 900 500]]


In [13]:
# The second task
import numpy as np
array = np.random.randint(low=0, high=1000, size=(5, 5))
print("The original matrix:", array, sep="\n", end="\n\n")
matrix = array[1:3, 2:4]
print("The new matrix:", matrix, sep="\n")

The original matrix:
[[156 687 967 152 108]
 [799 490  55  59 419]
 [536 666 856 295 835]
 [220 563  47 724 267]
 [547 780  18 476 767]]

The new matrix:
[[ 55  59]
 [856 295]]


In [14]:
# The third task
import numpy as np
vector = np.arange(21)
print("The initial vector of values:", vector, sep="\n", end="\n\n")
vector[9:16] = vector[9:16] * -1
print("The new vector of values:", vector, sep="\n")

The initial vector of values:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

The new vector of values:
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [15]:
# The fourth task
import numpy as np
from random import randint
array = np.random.randint(low=0, high=1000, size=(5, 5)).astype(float)
for i in range(5):
    for j in range(randint(1, 5)):
        array[i][randint(0, 4)] = np.nan
print("The original matrix:", array, sep="\n", end="\n\n")
matrix = np.nansum(array, axis=1) / 5
print("Average values:", matrix, sep="\n")

The original matrix:
[[632. 376. 609.  nan  nan]
 [776.  nan 998.  nan  nan]
 [ nan  nan 416.  nan 652.]
 [543.  nan  nan  nan  90.]
 [ nan  nan 635. 704. 868.]]

Average values:
[323.4 354.8 213.6 126.6 441.4]
